# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18v0OEw2xrs5vISyS7aYS0FjdiyaiBZ4v
"""

import streamlit as st
import numpy as np
import pandas as pd
import pickle

with open('model.pkl','rb') as file:
  model = pickle.load(file)

st.title("STOCK PREDICITION")
st.markdown('Enter the details below to predict the tommorow opening price of Jubliant Foodworks Limited:')
volume=st.number_input('Enter the todays Volume')
high=st.number_input('Enter the todays High')
low=st.number_input('Enter the todays Low')
open=st.number_input('Enter the todays Open')

if st.button("PREDICT"):
  data=np.array([[volume,high,low,open]])
  model.predict(data)