# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YhUFZzZ3xHkVIbj32s2O956qHJ3_jwu6
"""

from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import pandas as pd

iris = load_iris()

df = pd.DataFrame(data=iris.data, columns=iris.feature_names)

print(iris.feature_names)

df.head()

print(iris.target)

#Encodes the flower name which is in string data type
df['target'] = iris.target

df.head()

df.tail()

df['species'] = df['target'].map({0: 'setosa', 1: 'versicolor', 2: 'virginica'})

df.head()

df.tail()

X = df.drop(['target', 'species'], axis=1)
y = df['target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

clf = DecisionTreeClassifier()

clf.fit(X_train, y_train)

predictions = clf.predict(X_test)
print(predictions)

accuracy = accuracy_score(y_test, predictions)
print("Accuracy:", accuracy)

print("\nEnter flower details to predict species:")
sepal_length = float(input("Sepal length (cm): "))
sepal_width = float(input("Sepal width (cm): "))
petal_length = float(input("Petal length (cm): "))
petal_width = float(input("Petal width (cm): "))
user_input = [[sepal_length, sepal_width, petal_length, petal_width]]
prediction = clf.predict(user_input)[0]
predicted_species = iris.target_names[prediction]
print("\n🌸 The predicted species is:", predicted_species)

#Decodes the flower name with the target value
print(iris.target_names)

df.head()