# -*- coding: utf-8 -*-
"""graphs

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yW_hawuHuJfUR9yhqBOy5ItJdYIE6jhQ
"""

import matplotlib.pyplot as plt
import seaborn as sns

tips=sns.load_dataset("tips")

tips

sns.lineplot(x="day",y="total_bill",data=tips)
plt.xlabel('DAY')
plt.ylabel('TOTAL BILL')
plt.show()

sns.barplot(x="day",y="total_bill",data=tips)
plt.xlabel('DAY')
plt.ylabel('TOTAL BILL')
plt.show()

sns.scatterplot(x='day',y='total_bill',data=tips)
plt.xlabel('DAY')
plt.ylabel('TOTAL BILL')
plt.show()

sns.barplot(x='total_bill',y='tip',data=tips)
plt.xlabel('TOTAL BILL')
plt.ylabel('TIP')
plt.show()

sns.boxplot(x="day",y="total_bill",data=tips)
plt.xlabel('TOTAL BILL')
plt.ylabel('TIP')
plt.show()

sns.violinplot(x='day',y='total_bill',data=tips)
plt.xlabel('TOTAL BILL')
plt.ylabel('TIP')
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
iris = sns.load_dataset('iris')
sns.pairplot(iris, hue='species')
plt.show()

iris=sns.load_dataset("iris")
correlation_matrix=iris.drop('species', axis=1).corr()
sns.heatmap(correlation_matrix,annot=True,cmap="coolwarm")
plt.show()

titanic=ss.load_dataset("titanic")
ss.countplot(x="class",data=titanic)
plt.xlabel("passenger class")
plt.ylabel("count")
plt.show()

ss.jointplot(x="total_bill", y="tip", data=tips, kind="hex")
plt.title=("average total bill by day")
plt.xlabel("day of the week")
plt.ylabel("total bill")
plt.show()