# -*- coding: utf-8 -*-
"""selftraining.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dGLvXHDqvIsp-nNHwNduY40efh96-n93
"""

import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.semi_supervised import SelfTrainingClassifier
from sklearn.preprocessing import LabelEncoder
import numpy as np

df=pd.read_csv('/content/titanic.csv')

df.head()

df = df[["Survived", "Pclass", "Sex", "Age", "Fare"]].dropna()

le = LabelEncoder()
df["Sex"] = le.fit_transform(df["Sex"])

np.random.seed(42)
mask = np.random.rand(len(df)) < 0.5
df.loc[mask, "Survived"] = -1

X = df.drop("Survived", axis=1)
y = df["Survived"]

base_model = LogisticRegression()

self_training_model = SelfTrainingClassifier(base_model, criterion='k_best')

self_training_model.fit(X, y)

df["Predicted_Label"] = self_training_model.predict(X)

print(df.head(20))