# -*- coding: utf-8 -*-
"""social_Networks_ad.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1055qql15w4-qVUDgY98VpOHkn3Iv7-ee
"""

import pandas as pd
from sklearn.linear_model import LogisticRegression

ad=pd.read_csv('/content/advertising.csv')

ad.head()

ad.isnull().sum()

indep=ad[['Age','Area Income','Male',]]
dep=ad['Clicked on Ad']

log=LogisticRegression()

log.fit(indep,dep)

ag=int(input("Enter the Age:"))
sal=float(input("Enter the Area Income:"))
gen=int(input("Enter 0 for Male, 1 for Female:"))
ans=log.predict([[ag,sal,gen]])
if(ans==1):
  print("The person will click on the ad")
else:
  print("The person will not click on the ad")

from sklearn.metrics import accuracy_score
pval=log.predict(indep)
accuracy_score(dep,pval)